[metadata]
id = "CON30-C"
type = "rule"
category = "CON"
number = 30
title = "Clean up thread-specific storage"
description = """
The tss_create() function creates a thread-specific storage pointer identified
by a key. Threads can allocate thread-specific storage and associate the storage
with a key that uniquely identifies the storage by calling the tss_set()
function. If not properly freed, this memory may be leaked. Ensure that thread-
specific storage is freed.
"""
severity = "Medium"
likelihood = "Unlikely"
priority = "P2"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 05, 2025"

[rules.cert_c.CON30-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/CON30-C.+Clean+up+thread-specific+storage"
