[metadata]
id = "INT07-C"
type = "recommendation"
category = "INT"
number = 7
title = "Use only explicitly signed or unsigned char type for numeric values"
description = """
The three types char, signed char, and unsigned char are collectively called the
character types. Compilers have the latitude to define char to have the same
range, representation, and behavior as either signed char or unsigned char.
Irrespective of the choice made, char is a separate type from the other two and
is not compatible with either.
Use only signed char and unsigned char types for the storage and use of numeric
values because it is the only portable way to guarantee the signedness of the
character types (see STR00-C. Represent characters using an appropriate type for
more information on representing characters).
"""
severity = "Medium"
likelihood = "Probable"
priority = "P12"
level = "L1"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 20, 2025"

[rules.cert_c.INT07-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/INT07-C.+Use+only+explicitly+signed+or+unsigned+char+type+for+numeric+values"
cwe = []
related_cwe = ["CWE-682"]
