[metadata]
id = "ERR02-C"
type = "recommendation"
category = "ERR"
number = 2
title = "Avoid in-band error indicators"
description = """
Avoid in-band error indicators while designing interfaces. This practice is
commonly used by C library functions but is not recommended. One example from
the C Standard of a troublesome in-band error indicator is EOF (see FIO34-C.
Distinguish between characters read from a file and EOF or WEOF). Another
problematic use of in-band error indicators from the C Standard involving the
size_t and time_t types is described by
- INT31-C. Ensure that integer conversions do not result in lost or
misinterpreted data
- FLP07-C. Cast the return value of a function that returns a floating-point
type
- INT18-C. Evaluate integer expressions in a larger size before comparing or
assigning to that size
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P1"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Jun 17, 2025"

[rules.cert_c.ERR02-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/ERR02-C.+Avoid+in-band+error+indicators"
