[metadata]
id = "DCL05-C"
type = "recommendation"
category = "DCL"
number = 5
title = "Use typedefs of non-pointer types only"
description = """
Using type definitions (typedef) can often improve code readability. However,
type definitions to pointer types can make it more difficult to write const
-correct code because the const qualifier will be applied to the pointer type,
not to the underlying declared type.
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P2"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 19, 2025"

[rules.cert_c.DCL05-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/DCL05-C.+Use+typedefs+of+non-pointer+types+only"
