[metadata]
id = "STR02-C"
type = "recommendation"
category = "STR"
number = 2
title = "Sanitize data passed to complex subsystems"
description = """
String data passed to complex subsystems may contain special characters that can
trigger commands or actions, resulting in a software vulnerability. As a result,
it is necessary to sanitize all string data passed to complex subsystems so that
the resulting string is innocuous in the context in which it will be
interpreted.
These are some examples of complex subsystems:
- Command processor via a call to system() or similar function (also addressed
in ENV03-C. Sanitize the environment when invoking external programs)
- External programs
- Relational databases
- Third-party commercial off-the-shelf components (for example, an enterprise
resource planning subsystem)
"""
severity = "High"
likelihood = "Likely"
priority = "P9"
level = "L2"
cert_version = "2016 Edition (Wiki)"
last_modified = "Jul 24, 2025"

[rules.cert_c.STR02-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/STR02-C.+Sanitize+data+passed+to+complex+subsystems"
cwe = ["CWE-78", "CWE-90"]
related_cwe = ["CWE-88"]
