[metadata]
id = "FIO20-C"
type = "recommendation"
category = "FIO"
number = 20
title = "Avoid unintentional truncation when using fgets() or fgetws()"
description = """
The fgets() and fgetws() functions are typically used to read a newline-
terminated line of input from a stream. Both functions read at most one less
than the number of narrow or wide characters specified by an argument n from a
stream to a string. Truncation errors can occur if n - 1 is less than the number
of characters appearing in the input string prior to the new-line narrow or wide
character (which is retained) or after end-of-file. This can result in the
accidental truncation of user input.
"""
severity = "Medium"
likelihood = "Likely"
priority = "P12"
level = "L1"
cert_version = "2016 Edition (Wiki)"
last_modified = "Jul 24, 2025"

[rules.cert_c.FIO20-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152445"
