[metadata]
id = "CON37-C"
type = "rule"
category = "CON"
number = 37
title = "Do not call signal() in a multithreaded program"
description = """
Calling the signal() function in a multithreaded program is undefined behavior.
(See undefined behavior 135.)
"""
severity = "Low"
likelihood = "Probable"
priority = "P4"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 06, 2025"

[rules.cert_c.CON37-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/CON37-C.+Do+not+call+signal%28%29+in+a+multithreaded+program"
