[metadata]
id = "API10-C"
type = "recommendation"
category = "API"
number = 10
title = "APIs should have security options enabled by default"
description = """
APIS should have security options enabled by default– for example, having best
practice cipher suites enabled by default (something that changes over time)
while disabling out-of-favor cipher suites by default. When interface stability
is also a design requirement, an interface can meet both goals by providing off-
by-default options that produce stable behavior, such as
TLS_ENABLE_Y2015_BEST_PRACTICE_CIPHERS_ONLY.
"""
severity = "Medium"
likelihood = "Likely"
priority = "P6"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 20, 2025"

[rules.cert_c.API10-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/API10-C.+APIs+should+have+security+options+enabled+by+default"
