[metadata]
id = "SIG01-C"
type = "recommendation"
category = "SIG"
number = 1
title = "Understand implementation-specific details regarding signal handler persistence"
description = """
The signal() function has implementation-defined behavior and behaves
differently on Windows, for example, than it does on many UNIX systems.
The following code example shows this behavior:
Many UNIX (and UNIX-like) systems automatically reinstall signal handlers upon
handler execution, meaning that the signal handler defined by the user is left
in place until it is explicitly removed. For example, when this code is compiled
with GCC 3.4.4 and executed under Red Hat Linux, SIGINT is captured both times
by handler:
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P1"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 20, 2025"

[rules.cert_c.SIG01-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/SIG01-C.+Understand+implementation-specific+details+regarding+signal+handler+persistence"
