[metadata]
id = "FIO17-C"
type = "recommendation"
category = "FIO"
number = 17
title = "Do not rely on an ending null character when using fread()"
description = """
The fread() function, as defined in the C Standard, subclause 7.21.8.1 [ISO/IEC
9899:2011], does not explicitly null-terminate the read character sequence.
Synopsissize_t fread(void * restrict ptr, size_t size, size_t nmemb, FILE *
restrict stream) Description The fread function reads, into the array pointed to
by ptr, up to nmemb elements whose size is specified by size, from the stream
pointed to by stream.
Although the content of a file has a properly null-terminated character
sequence, if nmemb is less than the total length of the characters, the fread()
function will not read after nmemb characters. fread() will not append a null
character to the end of the string being read to.
"""
severity = "Low"
likelihood = "Likely"
priority = "P6"
level = "L2"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 20, 2025"

[rules.cert_c.FIO17-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152233"

[presets]
default = "not_enforced"
strict = "not_enforced"
pedantic = "not_enforced"
differs = false
overlap = "STR32-C"
basis = "no. Not enforced in any preset."
ruling = "FIO17-C/2026-09-26/disposition"
