[metadata]
id = "EXP16-C"
type = "recommendation"
category = "EXP"
number = 16
title = "Do not compare function pointers to constant values"
description = """
Comparing a function pointer to a value that is not a null function pointer of
the same type will be diagnosed because it typically indicates programmer error
and can result in unexpected behavior. Implicit comparisons will be diagnosed,
as well.
"""
severity = "Low"
likelihood = "Likely"
priority = "P6"
level = "L2"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 20, 2025"

[rules.cert_c.EXP16-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/EXP16-C.+Do+not+compare+function+pointers+to+constant+values"
cwe = ["CWE-480"]
related_cwe = ["CWE-482"]
