[metadata]
id = "INT30-C"
type = "rule"
category = "INT"
number = 30
title = "Ensure that unsigned integer operations do not wrap"
description = """
The C Standard, 6.2.5, paragraph 11 [ISO/IEC 9899:2024], states
A computation involving unsigned operands can never produce an overflow, because
arithmetic for the unsigned type is performed modulo 2^ N.
This behavior is more informally called unsigned integer wrapping. Unsigned
integer operations can wrap if the resulting value cannot be represented by the
underlying representation of the integer. The following table indicates which
operators can result in wrapping:
The following sections examine specific operations that are susceptible to
unsigned integer wrap. When operating on integer types with less precision than
int, integer promotions are applied. The usual arithmetic conversions may also
be applied to (implicitly) convert operands to equivalent types before
arithmetic operations are performed. Programmers should understand integer
conversion rules before trying to implement secure arithmetic operations. (See
INT02-C. Understand integer conversion rules.)
"""
severity = "High"
likelihood = "Likely"
priority = "P9"
level = "L2"
cert_version = "2016 Edition (Wiki)"
last_modified = "Oct 29, 2025"

[rules.cert_c.INT30-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/INT30-C.+Ensure+that+unsigned+integer+operations+do+not+wrap"
cwe = ["CWE-190", "CWE-191", "CWE-680"]
related_cwe = ["CWE-131"]
