[metadata]
id = "CON08-C"
type = "recommendation"
category = "CON"
number = 8
title = "Do not assume that a group of calls to independently atomic methods is atomic"
description = """
A consistent locking policy guarantees that multiple threads cannot
simultaneously access or modify shared data. When two or more operations must be
performed as a single atomic operation, a consistent locking policy must be
implemented using some form of locking, such as a mutex. In the absence of such
a policy, the code is susceptible to race conditions.
When presented with a set of operations, where each is guaranteed to be atomic,
it is tempting to assume that a single operation consisting of individually-
atomic operations is guaranteed to be collectively atomic without additional
locking. A grouping of calls to such methods requires additional synchronization
for the group.
Compound operations on shared variables are also non-atomic. See CON07-C. Ensure
that compound operations on shared variables are atomic for more information.
"""
severity = "Low"
likelihood = "Probable"
priority = "P2"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Unknown"

[rules.cert_c.CON08-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/CON08-C.+Do+not+assume+that+a+group+of+calls+to+independently+atomic+methods+is+atomic"
cwe = []
related_cwe = ["CWE-362", "CWE-662"]
