[metadata]
id = "PRE30-C"
type = "rule"
category = "PRE"
number = 30
title = "Do not create a universal character name through concatenation"
description = '''
The C Standard supports universal character names that may be used in
identifiers, character constants, and string literals to designate characters
that are not in the basic character set. The universal character name \U
nnnnnnnn designates the character whose 8-digit short identifier (as specified
by ISO/IEC 10646) is nnnnnnnn. Similarly, the universal character name \u nnnn
designates the character whose 4-digit short identifier is nnnn (and whose
8-digit short identifier is 0000 nnnn).
The C Standard, 5.1.1.2, paragraph 4 [ISO/IEC 9899:2024], says
If a character sequence that matches the syntax of a universal character name is
produced by token concatenation (6.10.5.3), the behavior is undefined.
See also undefined behavior 3.
'''
severity = "Low"
likelihood = "Unlikely"
priority = "P2"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Oct 29, 2025"

[rules.cert_c.PRE30-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/PRE30-C.+Do+not+create+a+universal+character+name+through+concatenation"
