[metadata]
id = "POS36-C"
type = "rule"
category = "POS"
number = 36
title = "Observe correct revocation order while relinquishing privileges"
description = """
In case of set-user-ID and set-group-ID programs, when the effective user ID and
group ID are different from those of the real user, it is important to drop not
only the user-level privileges but also the group privileges. While doing so,
the order of revocation must be correct.
POSIX defines setgid() to have the following behavior [Open Group 2004]:
If the process has appropriate privileges, setgid() shall set the real group ID,
effective group ID, and the saved set-group-ID of the calling process to gid. If
the process does not have appropriate privileges, but gid is equal to the real
group ID or the saved set-group-ID, setgid() shall set the effective group ID to
gid; the real group ID and saved set-group-ID shall remain unchanged.
"""
severity = "High"
likelihood = "Probable"
priority = "P18"
level = "L1"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 05, 2025"

[rules.cert_c.POS36-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/POS36-C.+Observe+correct+revocation+order+while+relinquishing+privileges"
cwe = []
related_cwe = ["CWE-696"]
