[metadata]
id = "INT09-C"
type = "recommendation"
category = "INT"
number = 9
title = "Ensure enumeration constants map to unique values"
description = """
A C enumeration defines a type with a finite set of values represented by
identifiers known as enumeration constants, or enumerators. An enumerator is a
constant integer expression whose value is representable as an int. Although the
language allows multiple enumerators of the same type to have the same value, it
is a common expectation that all enumerators of the same type have distinct
values. However, defining two or more enumerators of the same type to have the
same value can lead to some nonobvious errors.
"""
severity = "Low"
likelihood = "Probable"
priority = "P4"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 20, 2025"

[rules.cert_c.INT09-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/INT09-C.+Ensure+enumeration+constants+map+to+unique+values"
