[metadata]
id = "PRE04-C"
type = "recommendation"
category = "PRE"
number = 4
title = "Do not reuse a standard header file name"
description = """
If a file with the same name as a standard header is placed in the search path
for included source files, the behavior is undefined.
The following table from the C Standard, subclause 7.1.2 [ISO/IEC 9899:2011],
lists these standard headers:
Do not reuse standard header file names, system-specific header file names, or
other header file names.
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P2"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Oct 01, 2025"

[rules.cert_c.PRE04-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/PRE04-C.+Do+not+reuse+a+standard+header+file+name"
