[metadata]
id = "INT12-C"
type = "recommendation"
category = "INT"
number = 12
title = "Do not make assumptions about the type of a plain int bit-field when used in an expression"
description = """
Bit-fields can be used to allow flags or other integer values with small ranges
to be packed together to save storage space.
It is implementation-defined whether the specifier int designates the same type
as signed int or the same type as unsigned int for bit-fields. According to the
C Standard [ISO/IEC 9899:2011], C integer promotions also require that "if an
int can represent all values of the original type (as restricted by the width,
for a bit-field), the value is converted to an int; otherwise, it is converted
to an unsigned int."
This issue is similar to the signedness of plain char, discussed in INT07-C. Use
only explicitly signed or unsigned char type for numeric values. A plain int
bit-field that is treated as unsigned will promote to int as long as its field
width is less than that of int because int can hold all values of the original
type. This behavior is the same as that of a plain char treated as unsigned.
However, a plain int bit-field treated as unsigned will promote to unsigned int
if its field width is the same as that of int. This difference makes a plain int
bit-field even trickier than a plain char.
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P1"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 20, 2025"

[rules.cert_c.INT12-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/INT12-C.+Do+not+make+assumptions+about+the+type+of+a+plain+int+bit-field+when+used+in+an+expression"
