[metadata]
id = "MSC39-C"
type = "rule"
category = "MSC"
number = 39
title = "Do not call va_arg() on a va_list that has an indeterminate value"
description = """
Variadic functions access their variable arguments by using va_start() to
initialize an object of type va_list, iteratively invoking the va_arg() macro,
and finally calling va_end(). The va_list may be passed as an argument to
another function, but calling va_arg() within that function causes the va_list
to have an indeterminate value in the calling function. As a result, attempting
to read variable arguments without reinitializing the va_list can have
unexpected behavior. According to the C Standard, 7.16, paragraph 3 [ISO/IEC
9899:2024],
If access to the varying arguments is desired, the called function shall declare
an object (generally referred to as ap in this subclause) having type va_list.
The object ap may be passed as an argument to another function; if that function
invokes the va_arg macro with parameter ap, the representation of ap in the
calling function is indeterminate and shall be passed to the va_end macro prior
to any further reference to ap. 295) A pointer to a va _ list can be created and
passed to another function, in which case the original function can make further
use of the original list after the other function returns.
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P2"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Aug 31, 2025"

[rules.cert_c.MSC39-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/MSC39-C.+Do+not+call+va_arg%28%29+on+a+va_list+that+has+an+indeterminate+value"
