[metadata]
id = "CON41-C"
type = "rule"
category = "CON"
number = 41
title = "Wrap functions that can fail spuriously in a loop"
description = """
Functions that can fail spuriously should be wrapped in a loop. The
atomic_compare_exchange_weak() and atomic_compare_exchange_weak_explicit()
functions both attempt to set an atomic variable to a new value but only if it
currently possesses a known old value. Unlike the related functions
atomic_compare_exchange_strong() and atomic_compare_exchange_strong_explicit(),
these functions are permitted to fail spuriously. This makes these functions
faster on some platforms—for example, on architectures that implement compare-
and-exchange using load-linked/store-conditional instructions, such as Alpha,
ARM, MIPS, and PowerPC. The C Standard, 7.17.7.4, paragraph 5 [ISO/IEC
9899:2024], describes this behavior:
A weak compare-and-exchange operation may fail spuriously. That is, even when
the contents of memory referred to by expected and object are equal, it may
return zero and store back to expected the same memory contents that were
originally there.
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P2"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Unknown"

[rules.cert_c.CON41-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/CON41-C.+Wrap+functions+that+can+fail+spuriously+in+a+loop"
