[metadata]
id = "FIO11-C"
type = "recommendation"
category = "FIO"
number = 11
title = "Take care when specifying the mode parameter of fopen()"
description = """
The C Standard identifies specific strings to use for the mode on calls to
fopen() and fopen_s(). C11 provides a new mode flag, x, that provides the
mechanism needed to determine if the file that is to be opened exists. To be
strictly conforming and portable, one of the strings from the following table
(adapted from the C Standard, subclause 7.21.5.2 [ISO/IEC 9899:2011]) must be
used:
Strings to Use for the Mode on Calls to fopen() and fopen_s()
If the mode string begins with one of these sequences, the implementation might
choose to ignore the remaining characters, or it might use them to select
different kinds of files.
"""
severity = "Medium"
likelihood = "Probable"
priority = "P4"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Oct 29, 2025"

[rules.cert_c.FIO11-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152174"
