[metadata]
id = "DCL12-C"
type = "recommendation"
category = "DCL"
number = 12
title = "Implement abstract data types using opaque types"
description = """
Abstract data types are not restricted to object-oriented languages such as C++
and Java. They should be created and used in C language programs as well.
Abstract data types are most effective when used with private (opaque) data
types and information hiding.
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P1"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 19, 2025"

[rules.cert_c.DCL12-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/DCL12-C.+Implement+abstract+data+types+using+opaque+types"
