"""Render the Juliet coverage report (docs/juliet-coverage.md).

Every function here takes `db` as a plain argument and never imports a
concrete DB class -- same discipline as `bench/render_docs.py`. `scripts/
generate_juliet_coverage.py` is the only caller inside this repo, and it
always uses `bench.db.BenchDB` against the local SQLite file.

CROSS-REPO CONTRACT. The
other caller is a `benchmarking_db` script that imports `render_juliet_
coverage` and hands it a Postgres-backed handle, so the same report can be
regenerated from the shared multi-node database instead of one checkout's
local runs (see this repo's CLAUDE.md on why the committed file must not
describe a single node's runs as a project measurement). That makes `db` an
implicit protocol owned by this module, same reasoning as render_docs.py's
`BenchDBLike`:

  `JulietCoverageDBLike` below declares the entire required surface -- four
  read-only accessors. Adding a call to anything outside it is a breaking
  change to the other repo's caller and belongs in that list first.

`get_rule_totals` and `get_cwe_detail` are the two accessors an earlier
fix already added to resolve the top-20-truncation and cwe_scan-mis-keying bugs
that a naive re-query here would otherwise reintroduce -- see their
docstrings in `bench/db.py`. `get_cwe_detail`'s `rule_count` field (added
alongside this module) is what lets `_rule_cwe_map` below distinguish "no
rule targets this CWE" from "a mapped rule ran and found nothing" without a
fifth accessor.
"""

from __future__ import annotations

from typing import Protocol


class JulietCoverageDBLike(Protocol):
    """The complete `db` surface this module uses. See CROSS-REPO CONTRACT."""

    def get_run(self, run_id: str) -> dict | None: ...
    def get_run_summary(self, run_id: str) -> dict: ...
    def get_cwe_detail(self, run_id: str, cwe_id: str) -> dict | None: ...
    def get_rule_totals(self, run_id: str) -> dict[str, dict]: ...


TOP_RULES_LIMIT = 18


def _cwe_description(cwe_dir_name: str) -> str:
    """'CWE121_Stack_Based_Buffer_Overflow' -> 'Stack based buffer overflow'."""
    parts = cwe_dir_name.split("_", 1)
    if len(parts) < 2:
        return cwe_dir_name
    return parts[1].replace("_", " ").strip()


def _categorize(per_cwe: list[dict]) -> dict[str, list[dict]]:
    """Bucket per-CWE rows the way the report's sections are organized."""
    perfect, high, medium, low, zero = [], [], [], [], []
    for c in per_cwe:
        tp, fp = c["tp_count"], c["fp_count"]
        rate = c["tp_rate_pct"]
        if tp == 0:
            zero.append(c)
        elif fp == 0:
            perfect.append(c)
        elif rate > 50:
            high.append(c)
        elif rate >= 33:
            medium.append(c)
        else:
            low.append(c)

    perfect.sort(key=lambda c: c["per_file_rate"], reverse=True)
    high.sort(key=lambda c: c["tp_rate_pct"], reverse=True)
    medium.sort(key=lambda c: c["tp_rate_pct"], reverse=True)
    low.sort(key=lambda c: c["tp_rate_pct"], reverse=True)
    zero.sort(key=lambda c: c["file_count"], reverse=True)
    return {"perfect": perfect, "high": high, "medium": medium, "low": low,
            "zero": zero}


def _rule_cwe_map(db: JulietCoverageDBLike, run_id: str,
                   per_cwe: list[dict]) -> tuple[dict[str, list[str]], dict[str, bool]]:
    """{rule_id: [cwe_id, ...]} sorted by that rule's tp_count in each CWE
    (highest first), and {cwe_id: has any rule mapped at all}, both derived
    from one get_cwe_detail call per CWE in the run.
    """
    pairs: dict[str, list[tuple[int, str]]] = {}
    has_rules: dict[str, bool] = {}
    for c in per_cwe:
        cwe_id = c["cwe_id"]
        detail = db.get_cwe_detail(run_id, cwe_id)
        if not detail:
            has_rules[cwe_id] = False
            continue
        has_rules[cwe_id] = detail.get("rule_count", 0) > 0
        for r in detail["top_tp_rules"]:
            pairs.setdefault(r["rule_id"], []).append((r["tp_count"], cwe_id))

    rule_cwes = {}
    for rule_id, tp_cwe in pairs.items():
        tp_cwe.sort(key=lambda pair: pair[0], reverse=True)
        rule_cwes[rule_id] = [cwe_id for _, cwe_id in tp_cwe]
    return rule_cwes, has_rules


def render_juliet_coverage(db: JulietCoverageDBLike, run_id: str,
                            source_note: str) -> str:
    """The full markdown text of docs/juliet-coverage.md for one run.

    `source_note` is the "Auto-generated by ... from ..." line -- callers
    say where their `db` actually reads from (a local SQLite path here, a
    Postgres run cited by id from benchmarking_db's caller) since this
    module has no way to know that about a `db` satisfying only the
    Protocol above.
    """
    run = db.get_run(run_id)
    version = run["sqc_version"] if run else None
    summary = db.get_run_summary(run_id)
    per_cwe = summary["per_cwe"]

    total_tp = sum(c["tp_count"] for c in per_cwe)
    total_fp = sum(c["fp_count"] for c in per_cwe)
    total_files = sum(c["file_count"] for c in per_cwe)
    total = total_tp + total_fp
    overall_tp_rate = total_tp / total * 100 if total else 0
    n_cwes = len(per_cwe)

    buckets = _categorize(per_cwe)
    rule_cwes, zero_has_rules = _rule_cwe_map(db, run_id, per_cwe)

    rule_totals = db.get_rule_totals(run_id)
    rules = sorted(rule_totals.values(), key=lambda r: r["tp"], reverse=True)
    rules = rules[:TOP_RULES_LIMIT]

    lines = []
    lines.append("# Juliet C Test Suite — Coverage Report")
    lines.append("")
    lines.append(
        f"**Version**: aurora-lint v{version} ({run_id})\n"
        f"**Overall**: {total_tp:,} TP / {total_fp:,} FP — "
        f"**{overall_tp_rate:.1f}% TP rate** across {n_cwes} CWEs "
        f"({total_files:,} files)"
    )
    lines.append("")
    lines.append(f"*{source_note}*")
    lines.append("")
    lines.append("---")
    lines.append("")

    perfect = buckets["perfect"]
    lines.append(f"## 100% Precision ({len(perfect)} CWEs — zero FP)")
    lines.append("")
    lines.append("| CWE | Description | TP | Files | Per-File |")
    lines.append("|-----|------------|---:|------:|--------:|")
    for c in perfect:
        desc = _cwe_description(c["cwe_dir_name"])
        lines.append(
            f"| {c['cwe_id']} | {desc} | {c['tp_count']} "
            f"| {c['file_count']} | {c['per_file_rate']:.1f}% |"
        )
    lines.append("")

    high = buckets["high"]
    lines.append(f"## High Precision (>50% TP rate, {len(high)} CWEs)")
    lines.append("")
    lines.append("| CWE | Description | TP | FP | TP Rate | Per-File |")
    lines.append("|-----|------------|---:|---:|--------:|--------:|")
    for c in high:
        desc = _cwe_description(c["cwe_dir_name"])
        lines.append(
            f"| {c['cwe_id']} | {desc} | {c['tp_count']} "
            f"| {c['fp_count']} | {c['tp_rate_pct']:.1f}% "
            f"| {c['per_file_rate']:.1f}% |"
        )
    lines.append("")

    medium = buckets["medium"]
    lines.append(f"## Medium Precision (33–50% TP rate, {len(medium)} CWEs)")
    lines.append("")
    lines.append("| CWE | Description | TP | FP | TP Rate | Per-File |")
    lines.append("|-----|------------|---:|---:|--------:|--------:|")
    for c in medium:
        desc = _cwe_description(c["cwe_dir_name"])
        lines.append(
            f"| {c['cwe_id']} | {desc} | {c['tp_count']} "
            f"| {c['fp_count']} | {c['tp_rate_pct']:.1f}% "
            f"| {c['per_file_rate']:.1f}% |"
        )
    lines.append("")

    low = buckets["low"]
    lines.append(f"## Low Precision (<33% TP rate, {len(low)} CWEs)")
    lines.append("")
    lines.append("| CWE | Description | TP | FP | TP Rate | Per-File |")
    lines.append("|-----|------------|---:|---:|--------:|--------:|")
    for c in low:
        desc = _cwe_description(c["cwe_dir_name"])
        lines.append(
            f"| {c['cwe_id']} | {desc} | {c['tp_count']} "
            f"| {c['fp_count']} | {c['tp_rate_pct']:.1f}% "
            f"| {c['per_file_rate']:.1f}% |"
        )
    lines.append("")

    zero = buckets["zero"]
    zero_with_files = [c for c in zero if c["file_count"] > 0]
    zero_no_files = [c for c in zero if c["file_count"] == 0]

    lines.append(f"## Zero Detection ({len(zero_with_files)} CWEs)")
    lines.append("")
    lines.append("| CWE | Description | Files | Notes |")
    lines.append("|-----|------------|------:|-------|")
    for c in zero_with_files:
        desc = _cwe_description(c["cwe_dir_name"])
        cwe_id = c["cwe_id"]
        if zero_has_rules.get(cwe_id, False):
            fp = c["fp_count"]
            note = f"0 TP, {fp} FP" if fp > 0 else "Rules mapped but no detections"
        else:
            note = "No rule mapped"
        lines.append(f"| {cwe_id} | {desc} | {c['file_count']} | {note} |")

    if zero_no_files:
        lines.append("")
        lines.append(
            f"*{len(zero_no_files)} additional CWEs had no test files: "
            + ", ".join(c["cwe_id"] for c in zero_no_files)
            + ".*"
        )
    lines.append("")

    lines.append("## Top Rules by TP Volume")
    lines.append("")
    lines.append("| Rule | TP | FP | FP Rate | Primary CWEs |")
    lines.append("|------|---:|---:|--------:|-------------|")
    for r in rules:
        tp, fp = r["tp"], r["fp"]
        total_r = tp + fp
        fp_rate = fp / total_r * 100 if total_r else 0
        primary = ", ".join(rule_cwes.get(r["rule_id"], [])[:4])
        lines.append(
            f"| {r['rule_id']} | {tp:,} | {fp:,} | {fp_rate:.1f}% | {primary} |"
        )
    lines.append("")

    return "\n".join(lines)
