[metadata]
id = "EXP34-C"
type = "rule"
category = "EXP"
number = 34
title = "Do not dereference null pointers"
description = """
Dereferencing a null pointer is undefined behavior.
On many platforms, dereferencing a null pointer results in abnormal program
termination, but this is not required by the standard. See " Clever Attack
Exploits Fully-Patched Linux Kernel " [Goodin 2009] for an example of a code
execution exploit that resulted from a null pointer dereference.
"""
severity = "High"
likelihood = "Likely"
priority = "P18"
level = "L1"
cert_version = "2016 Edition (Wiki)"
last_modified = "Aug 06, 2025"

[rules.cert_c.EXP34-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers"
cwe = ["CWE-476", "CWE-690"]
