#!/usr/bin/env python3
"""Assert the docs' self-description claims match their sources, and export
those facts for other consumers (Sphinx `docs/conf.py`, `sqc_paper`'s
cross-repo facts snapshot).

WHY THIS EXISTS

On 2026-09-03 eight files claimed a rule count and they gave three different
answers: README.md said 307 enabled / 311 implemented (correct),
docs/index.rst said 305 enabled, docs/configuration.rst and
docs/project-structure.rst said 306, docs/architecture.rst and
docs/testing-methodology.rst said 305, and docs/test-summary.md's generator
counted ENABLED rules under a heading reading "Implemented Rules", which is
where the confusion started -- 307 and 311 are both right, for different
questions, and the generated doc used the wrong word for one of them.

Nothing noticed, because the enabled count moves whenever a rule is toggled
in the default manifest and no doc is regenerated when it does. This is the
same failure mode README's BENCH:HIGHLIGHTS marker block solves for benchmark
figures: a number in prose goes stale silently.

Originally named check_rule_counts.py and scoped to that one fact. Renamed
2026-09-17 after a paper/README/docs reconciliation pass found the identical
failure shape recurring for other self-description facts this file did not
yet cover: how many rules consume the macro-expansion engine (CLAUDE.md
itself named a fixed 4-rule list that had already drifted to 16), and which
real-world codebases are in the corpus (several docs still said "nine" after
mbedtls/valkey/ventoy were added to data/benchmark_repos.json). See
docs/adr/0004 for the policy this generalizes: one source of truth per fact,
everything else derives from or is checked against it.

SCOPE, DELIBERATELY NARROW. This file only ever handles facts *derivable
from this checkout* -- a manifest, a source grep, a JSON pin list. It must
never grow a check for a MEASURED fact (precision, recall, TP/FP counts,
throughput): those come from Postgres via benchmarking_db, per ADR-0004, and
adding a second, locally-computed path for them here would recreate the
exact "which copy is current" problem that ADR exists to prevent. If you're
tempted to add one, the answer is `bench render-docs` / benchmarking_db's
refresh script, not this file.

WHAT IT CHECKS (hard-fail lint, unchanged behavior from check_rule_counts.py)

Two numbers, derived from the manifest itself:

    implemented  every [rules.cert_c.<ID>] block          (308)
    enabled      those blocks with `enabled = true`        (304)

and, counted on its own because its rules are not CERT C rules, the CWE
ruleset: every [rules.cwe.<ID>] block with `enabled = true` (3).

Then every phrasing in the docs that claims one of them. A claim of some
OTHER number fails, naming the file and line. Counts that are legitimately
neither -- test-fixture directory totals, test-case totals, per-category
figures -- are not matched by these patterns and are left alone.

Deliberately NOT a check that the two numbers have particular values: the
manifest is the source of truth, so enabling a rule should require no edit
here. It requires an edit to the docs, which is the point.

WHAT IT EXPORTS BUT DOES NOT (YET) LINT

`--export-json` also reports the macro-expansion engine's current rule-consumer
set and the real-world corpus's project list. Neither is wired into the
hard-fail lint above:

  - The macro-expansion consumer set is a growing LIST, not a scalar, and
    is awkward to lint as free prose without a fragile pattern per phrasing.
    docs/conf.py substitutes it directly instead (see that file) so the
    Sphinx-built pages never hardcode it at all; CLAUDE.md's own mention was
    fixed 2026-09-17 to point at this script's grep rather than a list.
  - The real-world project count is DELIBERATELY not enforced yet: this
    repo's own docs still say "nine" (data/benchmark_repos.json has twelve,
    since mbedtls/valkey/ventoy were added) and whether those three count
    toward an "audited real-world corpus" claim is an open editorial
    question gated on their ground_truth adjudication completeness.
    Wiring a hard-fail check against len(benchmark_repos.json) before that
    question is answered would break every unrelated doc commit for a
    number nobody has decided yet. Once it resolves, extending
    TARGETS/patterns here the same way
    ENABLED/IMPLEMENTED work is the mechanical follow-up -- do that, don't
    re-derive this reasoning.
"""

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "rules_templates" / "rules-all.toml"
REMOVED = ROOT / "rules_templates" / "removed-rules.toml"
BENCHMARK_REPOS = ROOT / "data" / "benchmark_repos.json"
README = ROOT / "README.md"

# Files that make a rule-count claim. docs/test-summary.md is generated by
# src/rules/cert_c/integration.rs, so it is checked too -- if a FRESH copy
# disagrees, the generator is wrong and regenerating will not help. It is
# gitignored, though, so a commit cannot depend on the copy a checkout happens
# to hold: one generated before a rule-count change goes stale and would
# block every commit until regenerated. So the hook (no flag) checks only
# tracked files and says when it skips one; `--generated` checks the
# generated files too, and CI's test job runs it straight after the
# `cargo test` that regenerates them.
TARGETS = [
    "src/lib.rs",
    "README.md",
    "docs/index.rst",
    "docs/configuration.rst",
    "docs/architecture.rst",
    "docs/project-structure.rst",
    "docs/testing-methodology.rst",
    "docs/benchmark-running.rst",
    "docs/bibliography.rst",
    "docs/interactive-ui.rst",
    "docs/tool-comparison.rst",
    "docs/test-summary.md",
]

# Each pattern must capture the number in group 1. Kept narrow on purpose:
# a pattern that matches too much turns this check into noise and gets
# disabled, which is worse than not having it.
#
# THREE questions, not two, now that the vocabulary has settled (2026-09-17
# correction -- this script's own IMPLEMENTED_PATTERNS used to check
# "implemented" phrasing against the TRACKED count, which is the exact bug
# this file exists to catch elsewhere, just relocated into the checker
# itself. Caught when fixing README.md's competitor table: writing the now-
# correct "307 rules implemented (311 tracked)" made this hook fail,
# because it still expected "implemented" text to equal 311):
#
#   tracked      every [rules.cert_c.<ID>] block, regardless of whether it
#                has code                                        (308)
#   enabled      manifest says `enabled = true`                  (304)
#   implemented  has a real .rs file under src/rules/cert_c/      (304)
#
# `enabled` and `implemented` coincide today (every enabled rule has code,
# and this project's workflow never enables a rule before writing one --
# see CLAUDE.md's rule-implementation checklist), so both pattern lists
# below check against the same `enabled` count. They stay separate lists
# because "implemented" and "enabled by default" are different claims that
# could diverge in the future (e.g. a rule shipped but disabled pending
# more testing) -- if that ever happens, split their expected values here
# too, don't just merge the lists back to make a failure go away.
TRACKED_PATTERNS = [
    r"\((\d{3})\s+tracked[;)]",
    r"(\d{3})\s+tracked rules?",
    r"of the (\d{3}) tracked rules",
    r"\*\*Tracked Rules:\*\*\s+(\d{3})",
    r"/\s*(\d{3})\s+tracked rules",
    r"(\d{3})\s+CERT C rules across 17 categories",
    r"(\d{3})\s+rules across 17 categories",
    r"\*\*(\d{3})\s+rules\*\*, 17 categories",
    r"(\d{3})\s+rules by category",
]
ENABLED_PATTERNS = [
    r"(\d{3})\s+(?:CERT C\s+)?rules?\s+enabled by default",
    r"enables?\s+(\d{3})\s+of the \d{3} tracked rules",
    r"\((\d{3})\s+enabled by default\)",
    r"all\s+(\d{3})\s+enabled rules",
    r"#\s*(\d{3})\s+of \d{3} rules enabled",
    r"-->\s*(\d{3})\s+CERT C rules applied",
    r"\*\*Enabled By Default:\*\*\s+(\d{3})",
    r"(\d{3})\s+enabled\s*/\s*\d+\s+implemented",
    r"rules,\s+(\d{3})\s+enabled by default",
]
# The CWE ruleset is counted on its own: its rules are not CERT C rules, so
# they are in none of the counts above.
CWE_PATTERNS = [
    r"(\d+)\s+CWE[- ]ruleset rules?",
    r"CWE ruleset(?: of|:)\s+(\d+)\s+rules?",
]
UNIMPLEMENTED_PATTERNS = [
    r"the (\d+) tracked but not yet implemented",
]

IMPLEMENTED_PATTERNS = [
    r"\*\*(\d{3})\s+(?:CERT C\s+)?rules?\*\*\s+implemented",
    r"(\d{3})\s+rules? (?:are )?implemented",
    r"\((\d{3})\s+implemented\)",
    r"implements\s+(\d{3})\s+rules",
    r"of the (\d{3}) implemented rules",
    r"\*\*Implemented Rules:\*\*\s+(\d{3})",
    r"^\s+-\s+(\d{3})\s+implemented$",
]

# Extracts README's own hand-maintained disclosure count. There is no
# manifest for this fact -- a confirmed-upstream-fix is an external event,
# not something this checkout can compute -- so README is treated as the
# canonical source and this just reads it back out, for export only.
DISCLOSURE_PATTERN = r"produced\s+(\d+)\s+disclosed defects.*?—\s*\*\*(\d+)\s+of\s+(\d+)\s+confirmed and fixed"


def manifest_counts(text: str) -> tuple[int, int]:
    blocks = re.findall(
        r"^\[rules\.cert_c\.([A-Z]+[0-9]+-C)\]\n((?:(?!^\[).*\n)*)", text, re.M)
    if not blocks:
        raise SystemExit(f"no [rules.cert_c.*] blocks found in {MANIFEST}")
    enabled = sum(
        1 for _, body in blocks
        if re.search(r"^\s*enabled\s*=\s*true", body, re.M))
    return len(blocks), enabled


def cwe_counts(text: str) -> tuple[int, int]:
    """[rules.cwe.<ID>] blocks in the default manifest, and how many of
    them are enabled."""
    blocks = re.findall(
        r"^\[rules\.cwe\.(CWE-[0-9]+)\]\n((?:(?!^\[).*\n)*)", text, re.M)
    enabled = sum(
        1 for _, body in blocks
        if re.search(r"^\s*enabled\s*=\s*true", body, re.M))
    return len(blocks), enabled


def removed_rule_ids() -> list[str]:
    """Ids in rules_templates/removed-rules.toml: rules the tool no longer
    ships (ADR-0013 Decision 4). They have no manifest block, so they are in
    neither count above; they are reported as their own fact."""
    if not REMOVED.is_file():
        return []
    with REMOVED.open("rb") as fh:
        return sorted(r["id"] for r in tomllib.load(fh).get("removed", []))


def macro_expand_consumers() -> list[str]:
    """Rule IDs of every src/rules/ file that calls macro_expand::*.

    Ground truth by construction: greps the actual call sites rather than
    trusting any doc's list, which is the whole point (see module docstring).
    """
    out = subprocess.run(
        ["grep", "-rl", "macro_expand::", str(ROOT / "src" / "rules")],
        capture_output=True, text=True, check=False)
    ids = set()
    for line in out.stdout.splitlines():
        m = re.search(r"/([A-Z]+[0-9]+-C)/", line)
        if m:
            ids.add(m.group(1))
    return sorted(ids)


def realworld_projects() -> list[str]:
    if not BENCHMARK_REPOS.is_file():
        return []
    data = json.loads(BENCHMARK_REPOS.read_text())
    return sorted(r["name"] for r in data.get("repos", []))


def disclosure_count() -> dict | None:
    if not README.is_file():
        return None
    m = re.search(DISCLOSURE_PATTERN, README.read_text(), re.S)
    if not m:
        return None
    total, confirmed, of_total = (int(g) for g in m.groups())
    return {"total": total, "confirmed": confirmed, "of_total": of_total,
            "consistent": total == confirmed == of_total}


def git_head() -> str:
    out = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                          capture_output=True, text=True, check=False)
    return out.stdout.strip() or "unknown"


def export_facts() -> dict:
    tracked, enabled = manifest_counts(MANIFEST.read_text())
    cwe_total, cwe_enabled = cwe_counts(MANIFEST.read_text())
    macro_rules = macro_expand_consumers()
    return {
        "source_commit": git_head(),
        "rules_total": tracked,
        "rules_enabled": enabled,
        "rules_disabled": tracked - enabled,
        "cwe_rules_total": cwe_total,
        "cwe_rules_enabled": cwe_enabled,
        "rules_removed": len(removed_rule_ids()),
        "rules_removed_ids": removed_rule_ids(),
        "macro_expand_rule_count": len(macro_rules),
        "macro_expand_rules": macro_rules,
        "realworld_project_count": len(realworld_projects()),
        "realworld_projects": realworld_projects(),
        "disclosures": disclosure_count(),
    }


# Untracked targets that a build or test run writes, and how to regenerate
# each. Only these are checked with --generated; any other untracked target
# is still skipped.
GENERATED = {
    "docs/test-summary.md": "cargo test --package aurora-lint --lib -- rules::cert_c",
}


def untracked(rels: list[str]) -> set[str]:
    """The paths in `rels` git does not track. Empty when git cannot answer
    (no checkout, e.g. a source tarball): every target is then checked,
    which is how this ran before it consulted git."""
    try:
        out = subprocess.run(["git", "-C", str(ROOT), "ls-files", "-z", "--", *rels],
                             capture_output=True, text=True, check=True).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return set()
    return set(rels) - set(filter(None, out.split("\0")))


def lint(include_generated: bool = False) -> int:
    tracked, enabled = manifest_counts(MANIFEST.read_text())
    _, cwe_enabled = cwe_counts(MANIFEST.read_text())
    print(f"{MANIFEST.relative_to(ROOT)}: "
          f"{tracked} tracked, {enabled} enabled by default (== implemented, "
          f"per this project's convention -- see the module docstring); "
          f"{cwe_enabled} CWE-ruleset rule(s) enabled")

    # A removed rule is gone from the tool, so a block for it here would put
    # it back in both counts while the loader drops it with a warning.
    removed = removed_rule_ids()
    blocks = set(re.findall(r"^\[rules\.cert_c\.([A-Z]+[0-9]+-C)\]", MANIFEST.read_text(), re.M))
    revived = sorted(set(removed) & blocks)
    if revived:
        print(f"\n{MANIFEST.relative_to(ROOT)} still has a block for removed rule(s) "
              f"{', '.join(revived)} (see {REMOVED.relative_to(ROOT)}): delete the rule's "
              f"src/rules/ directory and rebuild.")
        return 1
    print(f"{REMOVED.relative_to(ROOT)}: {len(removed)} removed rule(s), counted in neither total")

    bad = []
    checked = 0
    skip = untracked(TARGETS)
    for rel in TARGETS:
        path = ROOT / rel
        if not path.is_file():
            continue
        if rel in skip and not (include_generated and rel in GENERATED):
            how = (f"regenerate it with `{GENERATED[rel]}` and check it with "
                   f"--generated" if rel in GENERATED else "track it to check it")
            print(f"{rel}: not tracked by git, so not checked here; {how}")
            continue
        for lineno, line in enumerate(path.read_text().splitlines(), 1):
            for pats, expect, what in (
                    (TRACKED_PATTERNS, tracked, "tracked"),
                    (ENABLED_PATTERNS, enabled, "enabled"),
                    (IMPLEMENTED_PATTERNS, enabled, "implemented"),
                    (UNIMPLEMENTED_PATTERNS, tracked - enabled, "not yet implemented"),
                    (CWE_PATTERNS, cwe_enabled, "CWE-ruleset")):
                for pat in pats:
                    for m in re.finditer(pat, line, re.M):
                        checked += 1
                        got = int(m.group(1))
                        if got != expect:
                            bad.append((rel, lineno, what, got, expect,
                                        line.strip()[:96]))
    if bad:
        print(f"\n{len(bad)} stale rule count(s):\n")
        for rel, lineno, what, got, expect, ctx in bad:
            print(f"  {rel}:{lineno}  says {got} {what}, manifest says {expect}")
            print(f"      {ctx}")
        print("\nThe manifest is the source of truth. Update the docs, or "
              "-- if docs/test-summary.md is listed above, freshly generated -- fix\n"
              "src/rules/cert_c/integration.rs and re-run "
              "`cargo test --package aurora-lint --lib -- rules::cert_c`.")
        return 1
    print(f"{checked} rule-count claim(s) across "
          f"{len(TARGETS)} file(s): all consistent")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--export-json", action="store_true",
                         help="print all computed facts as JSON and exit 0, "
                              "skipping the hard-fail lint")
    parser.add_argument("--generated", action="store_true",
                        help="also check the untracked generated files (run "
                             "straight after regenerating them, as CI does)")
    args = parser.parse_args()

    if args.export_json:
        print(json.dumps(export_facts(), indent=2))
        return 0

    return lint(include_generated=args.generated)


if __name__ == "__main__":
    sys.exit(main())
