#!/usr/bin/env python3
"""Generate docs/juliet-coverage.md from the latest Juliet benchmark run.

Reads local data/benchmarks.db by construction (this repo stays Postgres-
blind -- see CLAUDE.md). A figure generated this way describes this
checkout's own runs, not the project's measurements; benchmarking_db's own
script drives the same rendering code (`bench.juliet_coverage.
render_juliet_coverage`) against sqc_bench Postgres for anything committed
as an official number.

Usage:
    python scripts/generate_juliet_coverage.py            # latest run
    python scripts/generate_juliet_coverage.py RUN_ID     # specific run
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bench.db import BenchDB  # noqa: E402
from bench.juliet_coverage import _categorize, render_juliet_coverage  # noqa: E402

OUT_PATH = Path(__file__).resolve().parent.parent / "docs" / "juliet-coverage.md"


def _resolve_run_id(db: BenchDB, requested: str | None) -> str:
    if requested:
        if not db.get_run(requested):
            print(f"Error: run '{requested}' not found", file=sys.stderr)
            sys.exit(1)
        return requested
    candidates = [r for r in db.list_runs() if r["status"] == "completed"]
    if not candidates:
        print("Error: no completed runs found", file=sys.stderr)
        sys.exit(1)
    candidates.sort(key=lambda r: r["finished_at"] or "", reverse=True)
    return candidates[0]["run_id"]


def main():
    db = BenchDB()
    run_id = _resolve_run_id(db, sys.argv[1] if len(sys.argv) > 1 else None)

    content = render_juliet_coverage(
        db, run_id,
        "Auto-generated by `scripts/generate_juliet_coverage.py` from "
        "`data/benchmarks.db`.")
    OUT_PATH.write_text(content)

    summary = db.get_run_summary(run_id)
    run = db.get_run(run_id)
    buckets = _categorize(summary["per_cwe"])
    zero_with_files = [c for c in buckets["zero"] if c["file_count"] > 0]
    print(f"Generated {OUT_PATH} from run {run_id} (v{run['sqc_version']})")
    print(
        f"  {len(summary['per_cwe'])} CWEs: {len(buckets['perfect'])} perfect, "
        f"{len(buckets['high'])} high, {len(buckets['medium'])} medium, "
        f"{len(buckets['low'])} low, {len(zero_with_files)} zero")


if __name__ == "__main__":
    main()
