#!/usr/bin/env python3
"""Keep a compile database preprocessable after its checkout is restored.

playbooks/setup-compile-commands.yml builds each real-world checkout under
bear (or CMake) to capture compile_commands.json, then restores the checkout
to pristine so `python -m bench corpus-check` stays green and no generated
*.c/*.h is scanned as if it were the project's own code. That restore also
deletes headers the build generated and the compile database still
#includes -- pure-ftpd's config.h, sqlite's sqlite_cfg.h, valkey's
jemalloc/jemalloc.h, libcrc's tab/gentab*.inc -- and nothing notices,
because the database itself survives. Every build-based tool driven from
the database (Infer, Frama-C, clang-tidy -p, aurora-lint's compile-commands
mode) then fails to preprocess those translation units: 222 of 458 in-scope
TUs across the suite before this existed, 52 of pure-ftpd's 53.

The generated files cannot simply be left in the checkout: most are *.h,
which aurora-lint dispatches on and corpus-check rightly flags. So this
copies them OUT of the checkout, into a stash directory next to the
playbook's other out-of-tree build scratch, and rewrites every entry in the
compile database to look there first. The checkout goes back to pristine;
the database keeps resolving.

Usage (run after the build, before the restore-to-pristine step):

    scripts/stash_compile_db_headers.py --checkout ~/toolchain/valkey \\
        --stash ~/toolchain/.cc_build/generated/valkey \\
        deps/jemalloc/include:jemalloc/jemalloc.h src:release.h

Each positional is INCLUDE_ROOT:PATH, both relative to the checkout:
INCLUDE_ROOT is the directory the compiler resolves the include against
(the `-I` the build used, or the including file's own directory for a
quoted include), PATH is the include spelling. `deps/jemalloc/include:
jemalloc/jemalloc.h` copies <checkout>/deps/jemalloc/include/jemalloc/
jemalloc.h to <stash>/deps/jemalloc/include/jemalloc/jemalloc.h and adds
`-I<stash>/deps/jemalloc/include` to every entry, so `#include
<jemalloc/jemalloc.h>` resolves exactly as it did during the build. A PATH
may climb with `..` (libcrc's src/crc32.c includes "../tab/gentab32.inc"):
the stash keeps the same relative layout and the include root directory is
always created, so the compiler's own path walk lands on the copy.

The -I is inserted directly after the compiler, ahead of the build's own
include flags, and the entry keeps whichever form (`arguments` list or
`command` string) it had. Re-running is safe: the stash is rebuilt from
scratch and an -I already present is not duplicated. Exits non-zero, having
changed nothing, if a named file is missing -- a build that did not produce
it is a playbook bug, not something to paper over.
"""

import argparse
import json
import os
import shlex
import shutil
import sys
from pathlib import Path


def parse_spec(spec: str) -> tuple[str, str]:
    root, sep, path = spec.partition(":")
    if not sep or not path:
        raise SystemExit(f"bad spec {spec!r}: expected INCLUDE_ROOT:PATH")
    return os.path.normpath(root), path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--checkout", required=True, type=Path,
                    help="the corpus checkout the build ran in")
    ap.add_argument("--stash", required=True, type=Path,
                    help="out-of-tree directory to copy the generated files into")
    ap.add_argument("--db", type=Path,
                    help="compile database to rewrite (default: <checkout>/compile_commands.json)")
    ap.add_argument("specs", nargs="+", metavar="INCLUDE_ROOT:PATH",
                    help="generated file to stash, relative to the checkout")
    args = ap.parse_args()

    checkout = args.checkout.resolve()
    stash = args.stash.resolve()
    db_path = (args.db or checkout / "compile_commands.json").resolve()
    specs = [parse_spec(s) for s in args.specs]

    missing = [os.path.join(r, p) for r, p in specs
               if not (checkout / r / p).is_file()]
    if missing:
        print("stash_compile_db_headers: not generated by the build: "
              + ", ".join(missing), file=sys.stderr)
        return 1
    if not db_path.is_file():
        print(f"stash_compile_db_headers: no compile database at {db_path}",
              file=sys.stderr)
        return 1

    if stash.exists():
        shutil.rmtree(stash)
    include_roots: list[str] = []
    for root, path in specs:
        src = checkout / root / path
        dst = (stash / root / path).resolve()
        dst.parent.mkdir(parents=True, exist_ok=True)
        (stash / root).mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        inc = f"-I{stash / root}"
        if inc not in include_roots:
            include_roots.append(inc)

    entries = json.loads(db_path.read_text())
    rewritten = 0
    for entry in entries:
        if "arguments" in entry:
            argv = entry["arguments"]
            add = [i for i in include_roots if i not in argv]
            if add:
                entry["arguments"] = argv[:1] + add + argv[1:]
        else:
            argv = shlex.split(entry["command"])
            add = [i for i in include_roots if i not in argv]
            if add:
                entry["command"] = " ".join(
                    [argv[0]] + [shlex.quote(i) for i in add]
                    + [shlex.quote(a) for a in argv[1:]])
        rewritten += bool(add)
    db_path.write_text(json.dumps(entries, indent=1) + "\n")
    print(f"stashed {len(specs)} generated file(s) under {stash}; "
          f"added {' '.join(include_roots)} to {rewritten} of {len(entries)} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
