[metadata]
id = "ARR01-C"
type = "recommendation"
category = "ARR"
number = 1
title = "Do not apply the sizeof operator to a pointer when taking the size of an array"
description = """
The sizeof operator yields the size (in bytes) of its operand, which can be an
expression or the parenthesized name of a type. However, using the sizeof
operator to determine the size of arrays is error prone.
The sizeof operator is often used in determining how much memory to allocate via
malloc(). However using an incorrect size is a violation of MEM35-C. Allocate
sufficient memory for an object.
"""
severity = "High"
likelihood = "Probable"
priority = "P12"
level = "L1"
cert_version = "2016 Edition (Wiki)"
last_modified = "Jul 24, 2025"

[rules.cert_c.ARR01-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/ARR01-C.+Do+not+apply+the+sizeof+operator+to+a+pointer+when+taking+the+size+of+an+array"
cwe = []
related_cwe = ["CWE-467", "CWE-569", "CWE-783"]
