[metadata]
id = "MEM02-C"
type = "recommendation"
category = "MEM"
number = 2
title = "Immediately cast the result of a memory allocation function call into a pointer to the allocated type"
description = """
An object of type void * is a generic data pointer. It can point to any data
object. For any incomplete or object type T, C permits implicit conversion from
T * to void * or from void * to T *. C Standard memory allocation functions
aligned_alloc(), malloc(), calloc(), and realloc() use void * to declare
parameters and return types of functions designed to work for objects of
different types.
For example, the C library declares malloc() as
Calling malloc(s) allocates memory for an object whose size is s and returns
either a null pointer or a pointer to the allocated memory. A program can
implicitly convert the pointer that malloc() returns into a different pointer
type.
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P3"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 20, 2025"

[rules.cert_c.MEM02-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/MEM02-C.+Immediately+cast+the+result+of+a+memory+allocation+function+call+into+a+pointer+to+the+allocated+type"
