[metadata]
id = "MEM30-C"
type = "rule"
category = "MEM"
number = 30
title = "Do not access freed memory"
description = """
Evaluating a pointer—including dereferencing the pointer, using it as an operand
of an arithmetic operation, type casting it, and using it as the right-hand side
of an assignment—into memory that has been deallocated by a memory management
function is undefined behavior 183. Pointers to memory that has been deallocated
are called dangling pointers. Accessing a dangling pointer can result in
exploitable vulnerabilities.
According to the C Standard, using the value of a pointer that refers to space
deallocated by a call to the free() or realloc() function is undefined behavior.
(See undefined behavior 183.)
Reading a pointer to deallocated memory is undefined behavior 183 because the
pointer value is indeterminate and might be a trap representation. Fetching a
trap representation might perform a hardware trap (but is not required to).
"""
severity = "High"
likelihood = "Likely"
priority = "P9"
level = "L2"
cert_version = "2016 Edition (Wiki)"
last_modified = "Oct 29, 2025"

[rules.cert_c.MEM30-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/MEM30-C.+Do+not+access+freed+memory"
cwe = ["CWE-415", "CWE-416"]
related_cwe = ["CWE-666", "CWE-672", "CWE-758"]
