[metadata]
id = "FIO44-C"
type = "rule"
category = "FIO"
number = 44
title = "Only use values for fsetpos() that are returned from fgetpos()"
description = """
The C Standard, 7.23.9.3 paragraph 2 [ISO/IEC 9899:2024], defines the following
behavior for fsetpos():
The fsetpos function sets the mbstate_t object (if any) and file position
indicator for the stream pointed to by stream according to the value of the
object pointed to by pos, which shall be a value obtained from an earlier
successful call to the fgetpos function on a stream associated with the same
file.
Invoking the fsetpos() function with any other values for pos is undefined
behavior 181.
"""
severity = "Medium"
likelihood = "Unlikely"
priority = "P2"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 05, 2025"

[rules.cert_c.FIO44-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152071"
