[metadata]
id = "STR05-C"
type = "recommendation"
category = "STR"
number = 5
title = "Use pointers to const when referring to string literals"
description = """
The type of a narrow string literal is an array of char, and the type of a wide
string literal is an array of wchar_t. However, string literals (of both types)
are notionally constant and should consequently be protected by const
qualification. This recommendation is a specialization of DCL00-C. Const-qualify
immutable objects and also supports STR30-C. Do not attempt to modify string
literals.
Adding const qualification may propagate through a program; as const qualifiers
are added, still more become necessary. This phenomenon is sometimes called
const-poisoning. Const-poisoning can frequently lead to violations of EXP05-C.
Do not cast away a const qualification. Although const qualification is a good
idea, the costs may outweigh the value in the remediation of existing code.
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P3"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Aug 31, 2025"

[rules.cert_c.STR05-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/STR05-C.+Use+pointers+to+const+when+referring+to+string+literals"
